### ISSUE TITLE
Change the Pricebots/docs/README.md to include Bitcoin Price Bot

### ISSUE THREAD

**Issue by JordanDworaczyk** [JordanDworaczyk/Pricebots#17]
Provide links to @BTCPriceBot and vis versa

**Comment by JordanDworaczyk** [comment]
We will initiate this project once issue #22 is finished.

**Comment by JordanDworaczyk** [comment]
The README.md should include a link to the webpage which describes what Pricebots does, how it works, and how they can contribute or join the community.

**Comment by JordanDworaczyk** [comment]
# To-Dos
- [ ] Include list of pricebots on webpage so that people may follow the bots. 
- [ ] Webpage should describe what the bots do. 
- [ ] Webpage should describe how the bot works, such as, the dependencies and APIs that the bots use. 
- [ ] Anyone who visits the webpage should also know how to contribute and join the community on Slack.
# Implamentation 
In the docs folder there is a README.md file that is written in markdown. This file gets converted into a static webpage through githubs [gitpages](https://pages.github.com/). That is how we make the webpage. Anything that gets written in that file will be converted to a webpage. This webpage is the same website that is provided on the pricebots twittters so that people can click on it and see what the bot is about. You can see the current live page [here](https://jordandworaczyk.github.io/Pricebots/).
