### ISSUE TITLE
The bot should be able to run both @EthPriceBot and @BTCPriceBot

### ISSUE THREAD

**Issue by JordanDworaczyk** [JordanDworaczyk/Pricebots#22]
This can be implemented using an object-oriented design. 
[Here](https://jeffknupp.com/blog/2014/06/18/improve-your-python-python-classes-and-object-oriented-programming/) is a great resource for object-oriented design in python.
# Implementation 
We will be able to run multiple instances of twitter bots by using an object-oriented design. 
### Phase I 
We will translate current design into an object-oriented implementation. 
### Phase II 
We will fine tune class to be able to implement multiple instances of price bot.

### TO DO
- [x] Address what to do with the threader. How will the bot tweet on every hour for each instance. 
- [x] Consider the different timers for each method. 
- [x] Consider how the bot will shut down the windows for each chart.
- [x] Add color parameter for each bot. 
- [x] Create a watermark for BTCPriceBot.
- [x] Create a page for BTCPriceBot. 
- [x] Consider changing title of ETHPriceBot and BTCPriceBot to just PriceBots
- [ ] Test multiple bot instances for 24hrs. 
- [x] Change background of chart to transparent white.

**Comment by JordanDworaczyk** [comment]
Bot tweets every hour using the following while loop: 
```
twitter:
    consumer_key: WMKa5ds20Y5BmUcQz8o3oLslD
    consumer_secret: Z0UIFrva46quzUwM3OtRY3vJ80L2VVLtReuRB9WwPFvv4PWtcG
    access_key: 1523923351-08dEkDOkfjxZ31M8RBQy40eqdV9JicMD6NEQ7VJ
    access_secret: Cddg3NwALTFHAvqrF3UIYDX9VyWqCBKHkX0cS1WGE9o2h
bots:
    coin_name: eth
    full_name: Ethereum

```
